# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reconciliation.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14reconciliation.proto\"w\n\x15ReconciliationRequest\x12\x14\n\x0ctwin_tti_seq\x18\x01 \x01(\x04\x12\x18\n\x10twin_global_hash\x18\x02 \x01(\x0c\x12\x17\n\x0freconcile_epoch\x18\x03 \x01(\r\x12\x15\n\rwall_clock_us\x18\x04 \x01(\x04\"\x80\x01\n\x07UeState\x12\x0c\n\x04rnti\x18\x01 \x01(\r\x12\x0b\n\x03\x63qi\x18\x02 \x01(\r\x12\x12\n\nharq_state\x18\x03 \x03(\r\x12\x1b\n\x13scheduler_queue_age\x18\x04 \x01(\r\x12\x12\n\nbsr_kbytes\x18\x05 \x01(\r\x12\x15\n\rue_state_hash\x18\x06 \x01(\x0c\"\xac\x01\n\x16ReconciliationResponse\x12\x14\n\x0creal_tti_seq\x18\x01 \x01(\x04\x12\x1c\n\nfull_state\x18\x02 \x03(\x0b\x32\x08.UeState\x12\x18\n\x10real_global_hash\x18\x03 \x01(\x0c\x12\x14\n\x0chash_matched\x18\x04 \x01(\x08\x12\x17\n\x0freconcile_epoch\x18\x05 \x01(\r\x12\x15\n\rwall_clock_us\x18\x06 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reconciliation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECONCILIATIONREQUEST']._serialized_start=24
  _globals['_RECONCILIATIONREQUEST']._serialized_end=143
  _globals['_UESTATE']._serialized_start=146
  _globals['_UESTATE']._serialized_end=274
  _globals['_RECONCILIATIONRESPONSE']._serialized_start=277
  _globals['_RECONCILIATIONRESPONSE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
